#!/bin/zsh

var=$(cat ~/Documents/Text/KillList | dmenu)

[ $var = "transmission-da" ] && (pgrep -x $var > /dev/null || var='transmission-daemon')

pgrep -x $var > /dev/null && notify-send "$var already exists" || (($var &) && notify-send "Spawned $var" || notify-send "Failed spawning $var") 
