#!/bin/bash

setxkbmap -layout dk

xrdb ~/.Xresources

cat ~/.fehbg | tail -1 | grep "' '" && /home/adam/Documents/Scripts/Fordsmand-Sh/Background.sh || ~/.fehbg &

pgrep Titlebar.sh > /dev/null || ~/Documents/Scripts/Fordsmand-Sh/Titlebar.sh
pgrep dunst > /dev/null || dunst &
pgrep mullvad-vpn > /dev/null || mullvad-vpn &
pgrep spotifyd > /dev/null || spotifyd

~/Documents/Scripts/Fordsmand-Sh/Headset

