#!/bin/zsh

var=$(cat ~/Documents/Text/KillList | dmenu)

pgrep -x $var > /dev/null && (
    pgrep -x $var > /dev/null && killall -q $var > /dev/null && notify-send "Successfully killed $var" || notify-send "Failed killing $var"
) || (
    [ $var = "transmission-da" ] && (pgrep -x $var > /dev/null || var='transmission-daemon')

    pgrep -x $var > /dev/null && notify-send "$var already exists" || (($var &) && notify-send "Spawned $var" || notify-send "Failed spawning $var")
)
